name: Pull Request

on:
  pull_request:
  push:
    branches: [mainnet, devel, add_ci]

jobs:
  move-test:
    runs-on: ubuntu-latest
    container: mysten/sui-tools:mainnet 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: test
        run: cd contracts && sui move test
